name: Generate TOC

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: # allow manual runs

jobs:
  generate-toc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install doctoc
        run: npm install -g doctoc

      - name: Run doctoc
        run: doctoc .

      - name: Commit & push changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: update TOCs"
            git push
          else
            echo "No TOC updates needed"
          fi
