name: Update README with File List
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate File List
        run: |
          echo "## Repository Files" > FILES.md
          echo "" >> FILES.md
          find . -type f ! -path "./.git/*" ! -path "./.github/*" | sed 's|^./|- `|g' | sed 's|$|`|' >> FILES.md

      - name: Update README
        run: |
          sed -i '/## Repository Files/,$d' README.md
          cat FILES.md >> README.md
          rm FILES.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Auto-update README with file list" || exit 0
          git push
